name: linter

on: [push, pull_request_target]

jobs:
  make_test:  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
          
    - name: npm install
      run: make install
      
    - name: make lint
      run: make lint
      
